global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ec2'
    ec2_sd_configs:
      - region: ap-south-1
        access_key: YOUR_ACCESS_KEY
        secret_key: YOUR_SECRET_KEY
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
